FROM node:20-alpine

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

ARG AUTH_SERVICE_URL
ARG FARM_SERVICE_URL
ARG PRODUCT_SERVICE_URL
ARG ORDER_SERVICE_URL
ARG UPLOAD_SERVICE_URL

ENV AUTH_SERVICE_URL=$AUTH_SERVICE_URL
ENV FARM_SERVICE_URL=$FARM_SERVICE_URL
ENV PRODUCT_SERVICE_URL=$PRODUCT_SERVICE_URL
ENV ORDER_SERVICE_URL=$ORDER_SERVICE_URL
ENV UPLOAD_SERVICE_URL=$UPLOAD_SERVICE_URL

RUN npm run build

EXPOSE 3000

CMD ["npm", "start"]